### ISSUE TITLE
Platform specific constants accessed in enum_string_N.go causes compilation errors

### ISSUE THREAD

**Issue by johanhenriksson** [bbredesen/vk-gen#37]
Hey! 

First of all, exciting to see a new VK wrapper for Go! Im interested in evaluating it for my https://github.com/johanhenriksson/goworld project, and willing to contribute if it works out well :) I'd like to depend on a library that I could keep up to date myself if required.

I noticed there's been little testing on OSX, and indeed it does not seem to work at the moment. Tried to run one of the samples quickly, and im running in to these compilation errrors (excluded a bunch more similar ones):

```
# github.com/bbredesen/go-vk
../../../go/pkg/mod/github.com/bbredesen/go-vk@v0.0.0-20230304041510-33ed978b8bfd/enum_win32_string_0.go:21:9: undefined: FullScreenExclusiveEXT
../../../go/pkg/mod/github.com/bbredesen/go-vk@v0.0.0-20230304041510-33ed978b8bfd/enum_string_5.go:496:8: undefined: ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT
../../../go/pkg/mod/github.com/bbredesen/go-vk@v0.0.0-20230304041510-33ed978b8bfd/enum_string_6.go:975:8: undefined: STRUCTURE_TYPE_EXPORT_FENCE_WIN32_HANDLE_INFO_KHR
../../../go/pkg/mod/github.com/bbredesen/go-vk@v0.0.0-20230304041510-33ed978b8bfd/enum_string_6.go:976:8: undefined: STRUCTURE_TYPE_EXPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR
```

Most of them have `_WIN32` or `_NV` in their names, so I assume they are just platform specific constants not available on my platform. Perhaps they need to be moved into conditionally compiled files?

I haven't had a chance to look at the code generator yet, is there any support for keeping certain defines/code in platform specific go files?

**Comment by bbredesen** [comment]
The plan on the base issue here is is to remove go:build tags from the enum type files, but to leave them in place around commands, structs, extensions, etc. 

The enum files will still have their Vulkan platform names, and the platform-specific types will be generated to their own platform_string.go files, just without the build guards.
